services:
  # PostgreSQL 数据库
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-tracing_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      # 设置容器的系统时区
      TZ: Asia/Shanghai
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - app-network
  # NestJS API
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: api-production
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - TZ=Asia/Shanghai
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - database
    restart: unless-stopped
    networks:
      - app-network
    entrypoint: ["sh", "./entrypoint.sh"]
    # Nginx 前端代理
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    ports:
      - "80:80"
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
